name: budgetbuddy
description: A simple budget management app.
version: 0.0.2+3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  auto_route: 
  freezed:
  freezed_annotation: 
  json_serializable: 
  auto_route_generator: 
  path_provider:
  hooks_riverpod: 
  flutter_hooks:
  sembast:
  permission_handler: 
  dartz:
  circle_list: 
  flutter_launcher_icons: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:

flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
