name: budgetbuddy
description: A simple budget management app.
version: 0.0.2+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^4.0.1
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  auto_route_generator: ^4.0.0
  path_provider: ^2.0.10
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.4
  sembast: ^3.2.0+1
  permission_handler: ^9.2.0
  dartz: ^0.10.1
  circle_list: ^1.0.5
  flutter_launcher_icons: ^0.9.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
